### ISSUE TITLE
Create user stories

### ISSUE THREAD

**Issue by AwsSG** [AwsSG/paddys-pals#1]
Creating the initial user stories for the project, those stories will then be translated in coding tasks.

**Comment by bowets** [comment]
- As a person who has been in lockdown for a long time and has not seen their friends or had the opportunity to interact with people in an informal setting, I would like to meet new people and celebrate St. Patricks day so that I can have personal interaction with other people. 
	- As someone who values Irish culture, I want to connect with other like minded people so that we can celebrate St. Patricks Day
	- As someone who lives alone, I would like to interact and see other people so that I expand my social circle now and when the lockdown is over
	- As an extrovert, I want to talk to other people so that I can recharge my batteries and feel connected to others


	- As a person who is currently not from ireland I would like to enjoy St. Patricks day and explore the culture
	- As a person who is not from Ireland, I would like to see how Irish people celebrate St. Patricks day
	- As a person living alone, I would like to find other people who celebrate St. Patricks day so that I can learn and enjoy the culture

	- As a person wanting to celebrate this occasion, I want to be able to join others online through live feed
	- As a person wanting to celebrate, I want to be able to host a party through a live feed.
